# Site wide configuration

title: Quick & Tasty - Get Cooking!
description: "Quick and Tasty"
logo: W_160px.jpg
teaser: lino.jpg
locale: en_GB

#url: http://127.0.0.1/~wim/quickandtasty
url: http://10.0.1.3/~wim/quickandtasty


# Jekyll configuration
# For plugins
safe: true
sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Wim Vanderbauwhede
  web: http://www.quickandtastycooking.org.uk
  email: wimvanderbauwhede@yahoo.co.uk
  twitter: fuss_free_food
  bio: "Fuss-free food"
  avatar: W_160px.jpg # 160x160 px image for author byline

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
